## Chep.3

In [ ]:
#創立串列 並總和串列內的所有數值
expenses = [1138, 101, 12, 300, 2049, 100]
print(sum(expenses))

3700


In [ ]:
#建立串列 並print出索引的項目
expenses = [1138, 101, 12, 300, 2049]
print(expenses[0]) #索引從0開始 即1138
print(expenses[1])
print(expenses[-1]) #倒數第一個 即2049
print(expenses[-3])

1138
101
2049
12


In [ ]:
#建立多個串列並導入list 在呼叫清單中的串列項目
my_list0 = [] #空串列
my_list1 = list() 
my_list2 = ['python', 'javascript', 'C#']
print(my_list2[1])

javascript


In [ ]:
#要求list的長度
my_list2 = ['python', 'javascript', 'C#']
print(len(my_list2)) #求my_list2的整個長度
print(len(my_list2[2])) #求my_list2中指定資料的長度

3
2


In [ ]:
my_list2 = ['python', 'javascript', 'C#']
my_list2.append('java') #用append增加新資料到my_list2
print(my_list2)

['python', 'javascript', 'C#', 'java']


In [ ]:
my_list2 = ['python', 'javascript', 'C#']
my_list2.insert(2,'java') #用insert增加新資料到my_list2 並指定儲存順序
print(my_list2)

['python', 'javascript', 'java', 'C#']


In [ ]:
my_list2 = ['python', 'javascript', 'C#']
my_list2.remove('python') #刪除清單中指定的資料
print(my_list2)
del my_list2[-2] #刪除指定順序的資料
print(my_list2)
my_list2.clear() #刪除全部
print(my_list2)

['javascript', 'C#']
['C#']
[]


In [ ]:
#連續呼叫指定的串列
a=[1,3]
print(a*5)

[1, 3, 1, 3, 1, 3, 1, 3, 1, 3]


In [ ]:
a=[1,2,3,4,5,6,7,8,9]
b=a[0:3] #指定範圍，0,1,2不包含3
print(b)
c=a[0:9:2] #每一次取值都間隔2
print(c)
d = a[0: ]
print(d)
e = a[ :9]
print(e)
f = a[:] #取範圍裡全部的數值
print(f)

[1, 2, 3]
[1, 3, 5, 7, 9]
[1, 2, 3, 4, 5, 6, 7, 8, 9]
[1, 2, 3, 4, 5, 6, 7, 8, 9]
[1, 2, 3, 4, 5, 6, 7, 8, 9]


In [ ]:
a=[1,2,3,4,5,6,7,8,9]
del a[6:9] #刪除某範圍值,刪除第6、7、8的資料
print(a)
print(min(a)) #最小值
print(max(a)) #最大值
print(a.index(1)) #找出1所在的第一個索引值
b=[1,0,0,0,1,1]
print(b.count(1)) #1出現的次數
a.reverse() #串列反轉
print(a)
a.sort() #串列由小到大排序,a的值會被改變
print(a)

[1, 2, 3, 4, 5, 6]
1
6
0
3
[6, 5, 4, 3, 2, 1]
[1, 2, 3, 4, 5, 6]


In [ ]:
expenses = [1138, 101, 12, 300, 2049]
s=sorted(expenses) #expenses的值不會變 只將改變的資料回傳s
print(s, expenses)

[12, 101, 300, 1138, 2049] [1138, 101, 12, 300, 2049]


## chap3-1

Tuple (元組)

---


tuple(元組)可視為不可改變的串列，tuple跟list很像，但是我們不能新增、刪除或更新tuple的元素。tuple的好處有：

*   佔用較少空間
*   可當作dictionary(字典)的鍵值
*   可當作函式引數

In [ ]:
a_tuple=('python', 'js', 'SQL')
print(a_tuple)
b_list=['go', 'c#', 'vb']
b_tuple=tuple(b_list) #使串列不再改變
print(b_tuple)
print(b_tuple[0])

('python', 'js', 'SQL')
('go', 'c#', 'vb')
go


In [ ]:
#字典(dictionary - dict)為帶有鍵值(key)的串列(list)
languages = {}
languages = {'name':'python', 'version':'3.7'} #索引值(鍵值)可以自訂 #呼叫name即得到python
print(languages['name'])
print(languages['version'])
a={0:'python', 1:'java', 2:'SQL'}
print(a[0])
print(a[1])
print(a[2])
print(languages)
print(languages.keys()) #呼叫索引標籤
print(languages.values()) #呼叫索引標籤的值
print(languages.items()) #呼叫已經設定的所有項目
print('name' in languages) #判斷該標籤是否在指定清單

python
3.7
python
java
SQL
{'name': 'python', 'version': '3.7'}
dict_keys(['name', 'version'])
dict_values(['python', '3.7'])
dict_items([('name', 'python'), ('version', '3.7')])
True


## Chap.4 numpy套件(numeric python)

為什麼需要numpy?

---

*   numpy由c撰寫，速度快python 10~1000倍以上
*   numpy儲存結果較正確，python數字儲存不正確
*numpy節省記憶體儲存空間
*numpy的向量(矩陣計算)速度快
*numpy的取值方便


In [ ]:
a_list=[1,2,3,4]
print(a_list*3) #連續呼叫清單3次

[1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4]


In [ ]:
#numpy套件的ndarray型態,提供element-wise的操作
import numpy as np #載入套件
a=np.array([1,2,3,4,5,6]) #變更成數值
print(a*3) #將清單內的數值乘3再呼叫出來

[ 3  6  9 12 15 18]


In [ ]:
a=np.array([1,2,3,4,5])
print(type(a))
print(a.shape) #ndaary的形狀 
print(a.dtype) #資料的型態 #整數
print(a.ndim) #維度 #一維串列[]

<class 'numpy.ndarray'>
(5,)
int64
1


In [ ]:
import numpy as np
z=np.zeros(6) #將內置函數轉為0
print(z)
print(np.empty((2,3,4))) #轉為空串列 多維?
print(np.arange(10)) #呼叫範圍內的數值 0~9

[0. 0. 0. 0. 0. 0.]
[[[2.3991132e-316 0.0000000e+000 0.0000000e+000 0.0000000e+000]
  [0.0000000e+000 0.0000000e+000 0.0000000e+000 0.0000000e+000]
  [0.0000000e+000 0.0000000e+000 0.0000000e+000 0.0000000e+000]]

 [[0.0000000e+000 0.0000000e+000 0.0000000e+000 0.0000000e+000]
  [0.0000000e+000 0.0000000e+000 0.0000000e+000 0.0000000e+000]
  [0.0000000e+000 0.0000000e+000 0.0000000e+000 0.0000000e+000]]]
[0 1 2 3 4 5 6 7 8 9]


In [ ]:
my_array=np.arange(11) #設定0~10
print(my_array) #呼叫全部
print(my_array[0]) #呼叫第0項 
print(my_array[0:5]) #呼叫0到4項 不包含5

[ 0  1  2  3  4  5  6  7  8  9 10]
0
[0 1 2 3 4]


In [ ]:
my_2d_array=np.array([np.arange(0,5),np.arange(5,10)])
print(my_2d_array) #呼叫全部的串列資料
print(my_2d_array[1,:]) #呼叫第2個串列的全部資料
print(my_2d_array[:,1]) #呼叫兩個串列中的第1項資料
print(my_2d_array[1,1]) #呼叫第2個串列的第1項資料

[[0 1 2 3 4]
 [5 6 7 8 9]]
[5 6 7 8 9]
[1 6]
6


In [ ]:
my_array=np.arange(0,10) #設定範圍
print(my_array) #呼叫全部資料
print(my_array.shape) #呼叫串列形狀
my_2d_array=my_array.reshape(2,5) #改變串列形狀 2維 0~4項資料
print(my_2d_array)
print((np.arange(0,100).reshape(10,10))) #設定範圍後 改變串列形狀再呼叫

[0 1 2 3 4 5 6 7 8 9]
(10,)
[[0 1 2 3 4]
 [5 6 7 8 9]]
[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]


In [ ]:
b=np.array([56, 8, 19, 14, np.nan]) #np.nan 空值nan
print(b)

[56.  8. 19. 14. nan]


## Chep.5

In [ ]:
import math #套件 轉換成數學型態
radius = eval(input("請輸入圓的半徑：")) #把輸入的字串變成數學計算型態
print("圓的面積為：", radius * radius * math.pi)

請輸入圓的半徑：6
圓的面積為： 113.09733552923255


In [ ]:
import math
#計算面積
def circle_area(radius): #建立算式並回傳
    area = radius * radius * math.pi
    return area

print(circle_area(6)) #帶入指定半徑

113.09733552923255


## Chep.6

os套件：用來處理文件與目錄，與檔案相關操作

In [1]:
import os
print(os.getcwd()) #顯示目前所在的工作目錄

/content


In [2]:
#顯示目錄下的檔案
os.listdir(".")

['.config', 'sample_data']

In [3]:
#在原先目錄中新增目錄
os.makedirs("test")
os.listdir(".")

['.config', 'test', 'sample_data']

In [4]:
#移除指定的目錄
os.rmdir("test")
os.listdir(".")

['.config', 'sample_data']

# 檔案處理

---

os套件有自己的檔案處理命令，而比較常用的是python內建的open

*   w = 可寫(預設建立檔案) 若檔案存在則會清除舊檔案
*w+ = 可寫可讀(預設建立檔案) 若檔案存在則會清除舊檔案
*r = 可讀
*r+ = 可寫可讀 但寫入資料指向開頭
*a = 可寫不能讀 寫入資料指向尾端
*a+ = 可寫可讀 寫入資料指向尾端
*b = 轉為2進位文件
*ab+ = 2進位文件的讀寫 寫入資料指向尾端


In [8]:
a=open("a.txt","w") #新增檔案
a.write("This is a test1") #建立檔案
a.write("This is a test2\n")
a.write("This is a test3\n")
a.close() #關閉檔案

In [7]:
#檢查檔案是否存在
os.path.isfile("a.txt")

True

In [11]:
#讀取檔案
a=open("a.txt","r")
print(a.readline())
print(a.readline())
a.close()

This is a test1This is a test2

This is a test3



In [12]:
a=open("a.txt","r")
print(a.readlines())  #一次讀取多行，與a.read()命令相同
a.close()

['This is a test1This is a test2\n', 'This is a test3\n']


In [13]:
#加上檔案是否存在的判斷
if os.path.isfile("a.txt"): #if檔案存在
    a=open("a.txt","r")
    print(a.readlines())
    a.close()
else:
    print("檔案不存在") #若不存在才顯示

['This is a test1This is a test2\n', 'This is a test3\n']


# split函式

In [21]:
if os.path.isfile("a.txt"):
    a=open("a.txt","r")
    for line in a:
        fields=line.split(" ") #以空白為切割欄位
        print(fields)
    a.close()
else:
    print("檔案不存在")
        

檔案不存在


In [22]:
a=open("a.txt", "a")
a.write("This is test4\n") #附加新檔案進去
a.close()

a=open("a.txt","r")
print(a.readlines())
a.close()

['This is test4\n']


比較a與r+的不同

---



*   a寫在檔案的結尾
*   r+寫在檔案的開頭

In [23]:
a=open("a.txt","r+")
a.write("This is a test5\n") #附加的檔案會在開頭
a.close()

a=open("a.txt","r")
print(a.readlines())
a.close()

['This is a test5\n']


In [24]:
if os.path.isfile("a.txt"):
    os.remove("a.txt") #刪除檔案
    print("檔案刪除成功")
else:
    print("找不到檔案")
print(os.path.isfile("a.txt")) #判斷檔案是否存在

檔案刪除成功
False


## Chap.7 錯誤處理

---
*   try:
*   except:
*else:
*finally:

In [26]:
a=10
b=20
if a<b:
    print(n) #直接顯示錯誤

NameError: ignored

In [27]:
a=10
b=20
try: #運用try 發生錯誤則回傳錯誤產生 而非直接顯示錯誤
    if a<b:
        print(n)
except:
    print("錯誤產生")

錯誤產生


In [28]:
#指定錯誤類別處理
a=10
b=20
try:
    if a<b:
        print(n)
except NameError as e: #參數名稱錯誤
    print("錯誤產生, 錯誤原因：",e)
except ZeroDivisionError: #數值除以0錯誤
    print("除以0錯誤")

錯誤產生, 錯誤原因： name 'n' is not defined


In [29]:
#else
#沒有錯誤產生會執行的部分
a=10
b=20
try:
    if a>b: #改變比較條件，讓錯誤不發生
        print(n)
except:
    print("錯誤發生")
else: #用條件式顯示錯誤消息
    print("沒有錯誤發生時會執行的部分")

沒有錯誤發生時會執行的部分


In [30]:
a=10
b=20
try:
    if a>b: #改變比較條件，讓錯誤不發生
        print(n)
except:
    print("錯誤發生")
else: #用條件式顯示錯誤消息
    print("沒有錯誤發生時會執行的部分")
finally: #在所有條件執行後必定執行的部分
    print("不管有沒有錯誤一定會執行的部分")

沒有錯誤發生時會執行的部分
不管有沒有錯誤一定會執行的部分
